Revert "flashrom: Merge remote-tracking branch cros/main into factory-dedede-13683.B"
This reverts commit 18010db3c2724ebe16fec1a3aa709b0e1c9186ec.

Reason for revert: This impacts multiple project factory process, detailed issue please refer to https://b.corp.google.com/issues/190683178#comment30

Original change's description:
> flashrom: Merge remote-tracking branch cros/main into factory-dedede-13683.B
>
> Relevant changes from af48c5aa21 to 51cd1c0932
> Fix the build error:
> ./fmap.h:68:55: error: declaration of 'struct flashctx' will not be visible outside of this function [-Werror,-Wvisibility]
> int fmap_read_from_rom(struct fmap **fmap_out, struct flashctx *const flashctx, size_t rom_offset, size_t len);
>                                                       ^
> 1 error generated.
> make: *** [Makefile:1282: cros_ec.o] Error 1
> make: *** Waiting for unfinished jobs....
>
> BUG=b:190683178
> BRANCH=factory-dedede-13683.B
> TEST=XM25QH128CWIGT08S AVL test pass on Cret.
>
> Signed-off-by: Dtrain Hsu <dtrain_hsu@compal.corp-partner.google.com>
> Change-Id: Iac8220399afa3863fae6ef0eeb16944c22fedfdd
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/flashrom/+/3005146
> Reviewed-by: Henry Sun <henrysun@google.com>
> Commit-Queue: Henry Sun <henrysun@google.com>

Bug: b:190683178
Change-Id: Ie8d9830ed12c94f9f834e9a0501dc8b92d3ef417
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/flashrom/+/3032322
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Henry Sun <henrysun@google.com>
Reviewed-by: Shou-Chieh Hsu <shouchieh@chromium.org>
Commit-Queue: Henry Sun <henrysun@google.com>
Tested-by: Henry Sun <henrysun@google.com>