Revert "Merge remote-tracking branch cros/main into factory-dedede-13683.B"
This reverts commit 341349d8bd30d829340d2391c903c7f192499598.

Reason for revert: This CL breaks Dedede factory branch build - https://ci.chromium.org/ui/p/chromeos/builders/general/Factory/b8842990144668157520/overview
Error: 
flashrom-0.9.9-r1113: ./fmap.h:68:55: error: declaration of 'struct flashctx' will not be visible
flashrom-0.9.9-r1113:       outside of this function [-Werror,-Wvisibility]
flashrom-0.9.9-r1113: int fmap_read_from_rom(struct fmap **fmap_out, struct flashctx *const fl...
flashrom-0.9.9-r1113:              

Original change's description:
> Merge remote-tracking branch cros/main into factory-dedede-13683.B
>
> Relevant changes from af48c5aa21 to 8d35c87252
>
> BUG=b:190683178
> BRANCH=none
> TEST=XM25QH128CWIGT08S AVL test pass on Cret.
>
> Change-Id: I7c473276c647e106b296fc2462c23eb8c624230b
> Signed-off-by: Dtrain Hsu <dtrain_hsu@compal.corp-partner.google.com>
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/flashrom/+/2987613
> Reviewed-by: Shou-Chieh Hsu <shouchieh@chromium.org>
> Commit-Queue: Shou-Chieh Hsu <shouchieh@chromium.org>

Bug: b:190683178
Change-Id: I8c87e258f3288dc212e2594be8849608a233e3ea
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/flashrom/+/2999411
Auto-Submit: Henry Sun <henrysun@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Henry Sun <henrysun@google.com>
Reviewed-by: Shou-Chieh Hsu <shouchieh@chromium.org>
Tested-by: Henry Sun <henrysun@google.com>
Commit-Queue: Shou-Chieh Hsu <shouchieh@chromium.org>