flashrom: Merge remote-tracking branch cros/main into factory-dedede-13683.B
Relevant changes from af48c5aa21 to 51cd1c0932
Fix the build error:
./fmap.h:68:55: error: declaration of 'struct flashctx' will not be visible outside of this function [-Werror,-Wvisibility]
int fmap_read_from_rom(struct fmap **fmap_out, struct flashctx *const flashctx, size_t rom_offset, size_t len);
                                                      ^
1 error generated.
make: *** [Makefile:1282: cros_ec.o] Error 1
make: *** Waiting for unfinished jobs....

BUG=b:190683178
BRANCH=factory-dedede-13683.B
TEST=XM25QH128CWIGT08S AVL test pass on Cret.

Signed-off-by: Dtrain Hsu <dtrain_hsu@compal.corp-partner.google.com>
Change-Id: Iac8220399afa3863fae6ef0eeb16944c22fedfdd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/flashrom/+/3005146
Reviewed-by: Henry Sun <henrysun@google.com>
Commit-Queue: Henry Sun <henrysun@google.com>